In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
A = np . array ([[1 , 2] , [3 , 4]])
B = np . array ([[5 , 6] , [7 , 8]])

C = A + B # Cộng ma trận
D = A - B # Trừ ma trận

In [5]:
C

array([[ 6,  8],
       [10, 12]])

In [6]:
D

array([[-4, -4],
       [-4, -4]])

In [7]:
E = np.dot(A,B)
E

array([[19, 22],
       [43, 50]])

In [8]:
det_A = np . linalg . det ( A )

In [9]:
det_A

np.float64(-2.0000000000000004)

In [10]:
A_inv = np . linalg . inv ( A )
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
np.dot(A,A_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [12]:
rank_A = np . linalg . matrix_rank ( A )
rank_A

np.int64(2)

In [13]:
x = np . linalg . solve (A , B )
x

array([[-3., -4.],
       [ 4.,  5.]])

In [16]:
eig_values , eig_vectors = np . linalg . eig ( A )
print(eig_values ,'\n', eig_vectors)

[-0.37228132  5.37228132] 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [17]:
U , S , V = np . linalg . svd ( A )
print(U , S , V,sep = "\n------------\n")

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
------------
[5.4649857  0.36596619]
------------
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


# Vector - dot product

In [19]:
v1 = np.array([1,2,3,4])
v2 = np.array([2,3,4,5])
dot_product = np . dot ( v1 , v2 )
dot_product

np.int64(40)

In [21]:
norm_v = np . linalg . norm ( v1 )
norm_v

np.float64(5.477225575051661)

In [22]:
A_transpose = A . T
print(A)
print(A_transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


Bài 1

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
D = A-B
print(C)
print(D)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


Bai 3

In [24]:
E = A* B
E

array([[ 5, 12],
       [21, 32]])

bai 5

In [25]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(v1.dot(v2))

32


bai 6

In [27]:
!pip install scipy

   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   -----------------

In [28]:
from scipy import signal

In [35]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
K = [[1,0],
     [0, -1]]

convolved_image = signal.convolve2d(A, np.flip(K), mode='valid')


In [36]:
convolved_image

array([[-4, -4],
       [-4, -4]])