In [1]:
import numpy as np


In [ ]:

def compute_gram_matrix ( feature_map : np . ndarray ) -> np . ndarray :
    """
    Tính Gram Matrix từ feature map .
    Args :
        feature_map (np. ndarray ): Ma trận đặc trưng có kích thước (C, H, W).
    Returns :
        np. ndarray : Gram Matrix có kích thước (C, C).
    """
    # Lấy kích thước đầu vào
    C , H , W = feature_map . shape
    # Chuyển đổi ma trận về dạng (C, H*W)
    F = feature_map . reshape (C , H * W )
    # Tính Gram Matrix G = F @ F.T
    G = np . dot (F , F . T )
    # Chuẩn hóa bằng số điểm ảnh
    G /= ( H * W )
    return G

# Tạo dữ liệu giả lập với kích thước (3 , 4 , 4)
np . random . seed (42)
feature_map = np . random . rand (3 , 4 , 4)

# Tính Gram Matrix
gram_matrix = compute_gram_matrix ( feature_map )

# In kết quả
print (" Gram Matrix :\n", gram_matrix )

 Gram Matrix :
 [[0.33432857 0.2207897  0.27598961]
 [0.2207897  0.19580158 0.19452994]
 [0.27598961 0.19452994 0.32603015]]


In [3]:
!pip install torch

In [4]:
import torch
feature_map_torch = torch . tensor ( feature_map , dtype = torch . float32 )
F_torch = feature_map_torch . view (3 , -1)
gram_matrix_torch = torch . mm ( F_torch , F_torch . t () ) / (4 * 4)
print ("\ nGram Matrix PyTorch :\n", gram_matrix_torch . numpy () )

<>:5: SyntaxWarning: invalid escape sequence '\ '
<>:5: SyntaxWarning: invalid escape sequence '\ '
C:\Users\Admin\AppData\Local\Temp\ipykernel_15544\3659900989.py:5: SyntaxWarning: invalid escape sequence '\ '
  print ("\ nGram Matrix PyTorch :\n", gram_matrix_torch . numpy () )


\ nGram Matrix PyTorch :
 [[0.33432856 0.2207897  0.2759896 ]
 [0.2207897  0.19580159 0.19452995]
 [0.2759896  0.19452995 0.32603014]]


In [ ]:
import numpy as np
def compute_gram_matrix(feature_map: np.ndarray) -> np.ndarray:
    """
    Tính toán Gram matrix từ một feature map.
    Args:
        feature_map (np.ndarray): Feature map có kích thước (C, H, W),
                                 trong đó C là số kênh, H là chiều cao và W là chiều rộng.
    Returns:
        np.ndarray: Gram matrix có kích thước (C, C).
    """
    C, H, W = feature_map.shape
    F = feature_map.reshape(C, H * W)
    G = np.dot(F, F.T)
    G = G.astype(np.float64)  # Ép kiểu mảng G sang float64
    G /= float(H * W)  # Chuẩn hóa bằng cách chia cho số lượng phần tử trong mỗi feature map
    return G
# Feature Map đầu vào cố định
feature_map = np.array([
    [[1, 2], [3, 4]],  # Kênh 1
    [[5, 6], [7, 8]],  # Kênh 2
    [[9, 10], [11, 12]]  # Kênh 3
])
gram_matrix = compute_gram_matrix(feature_map)
print(gram_matrix)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]


In [14]:
import numpy as np

def compute_similarity ( gram1 : np . ndarray , gram2 : np . ndarray ) -> float :
    """
    Tính độ tương đồng giữa hai Gram Matrix .
    Args :
        gram1 (np. ndarray ): Gram Matrix ảnh 1.
        gram2 (np. ndarray ): Gram Matrix ảnh 2.
    Returns :
        float : Độ tương đồng trong khoảng [0 ,1].
    """
    # Your code here #
    G1_G2 = gram1*gram2
    s1 = np.sum(G1_G2)
    s2 = (
        np.sqrt(np.sum(np.square(gram1)))*
        np.sqrt(np.sum(np.square(gram2))))
    return s1/s2
    
    
    
    
# Feature Map của hai ảnh (Cần di chuyển ra ngoài hàm nếu muốn tái sử dụng hàm này)
feature_map1 = np . array ([
    [[1 , 2] , [3 , 4]] ,
    [[5 , 6] , [7 , 8]] ,
    [[9 , 10] , [11 , 12]]
])

feature_map2 = np . array ([
    [[2 , 4] , [6 , 8]] ,
    [[1 , 3] , [5 , 7]] ,
    [[0 , 2] , [4 , 6]]
])

# Tính Gram Matrix của hai ảnh
gram1 = compute_gram_matrix ( feature_map1 )
gram2 = compute_gram_matrix ( feature_map2 )
similarity = compute_similarity ( gram1 , gram2 )
print (" Similarity Score :", similarity )



 Similarity Score : 0.6741245785155123
